"""Curated plant seeds with correct scientific names for image/description matching."""
from __future__ import annotations

# Each seed must have a stable Wikipedia/species page match via scientific_name.
# Descriptions are filled from Wikipedia extracts at build time when available.

def _care(light: str, water: str, humidity: str) -> dict[str, str]:
    return {"light": light, "water": water, "humidity": humidity}


HOUSE = _care("Bright indirect light", "Water when the top inch of soil is dry", "Average household humidity")
HIGH = _care("Bright indirect light", "Keep lightly moist; never soggy", "High humidity")
SUCC = _care("Bright light to full sun", "Soak thoroughly, then let soil dry", "Low humidity")
SHADE = _care("Medium to low indirect light", "Water when top soil dries", "Average household humidity")
CARN = _care("Full sun to very bright light", "Keep in distilled/rain water; never fertilize soil", "High humidity")
ORCH = _care("Bright indirect light", "Water when bark mix is nearly dry", "Medium-high humidity")
HERB = _care("Full sun", "Even moisture; avoid drought", "Low to medium humidity")
OUTDOOR = _care("Full sun", "Deep water when soil is dry", "Outdoor ambient humidity")


CURATED_SEEDS: list[dict] = [
    # Featured / popular houseplants
    {
        "id": "venus-flytrap",
        "common_names": ["Venus flytrap", "Venus Flytrap"],
        "scientific_name": "Dionaea muscipula",
        "family": "Droseraceae",
        "care": CARN,
    },
    {
        "id": "monstera-deliciosa",
        "common_names": ["Monstera", "Swiss cheese plant", "Monstera deliciosa"],
        "scientific_name": "Monstera deliciosa",
        "family": "Araceae",
        "care": HOUSE,
    },
    {
        "id": "snake-plant",
        "common_names": ["Snake plant", "Mother-in-law's tongue"],
        "scientific_name": "Dracaena trifasciata",
        "family": "Asparagaceae",
        "care": SUCC,
    },
    {
        "id": "pothos",
        "common_names": ["Pothos", "Devil's ivy", "Golden pothos"],
        "scientific_name": "Epipremnum aureum",
        "family": "Araceae",
        "care": HOUSE,
    },
    {
        "id": "fiddle-leaf-fig",
        "common_names": ["Fiddle-leaf fig", "Fiddle leaf fig"],
        "scientific_name": "Ficus lyrata",
        "family": "Moraceae",
        "care": HOUSE,
    },
    {
        "id": "peace-lily",
        "common_names": ["Peace lily"],
        "scientific_name": "Spathiphyllum wallisii",
        "family": "Araceae",
        "care": HIGH,
    },
    {
        "id": "aloe-vera",
        "common_names": ["Aloe vera", "Aloe"],
        "scientific_name": "Aloe vera",
        "family": "Asphodelaceae",
        "care": SUCC,
    },
    {
        "id": "air-plant",
        "common_names": ["Air plant", "Sky plant"],
        "scientific_name": "Tillandsia ionantha",
        "family": "Bromeliaceae",
        "care": _care("Bright indirect light", "Soak weekly; dry fully after", "Medium humidity"),
    },
    {
        "id": "phalaenopsis-orchid",
        "common_names": ["Moth orchid", "Phalaenopsis"],
        "scientific_name": "Phalaenopsis amabilis",
        "family": "Orchidaceae",
        "care": ORCH,
    },
    {
        "id": "zz-plant",
        "common_names": ["ZZ plant", "Zanzibar gem"],
        "scientific_name": "Zamioculcas zamiifolia",
        "family": "Araceae",
        "care": SHADE,
    },
    {
        "id": "rubber-plant",
        "common_names": ["Rubber plant", "Rubber tree"],
        "scientific_name": "Ficus elastica",
        "family": "Moraceae",
        "care": HOUSE,
    },
    {
        "id": "spider-plant",
        "common_names": ["Spider plant"],
        "scientific_name": "Chlorophytum comosum",
        "family": "Asparagaceae",
        "care": HOUSE,
    },
    {
        "id": "chinese-money-plant",
        "common_names": ["Chinese money plant", "Pilea", "Missionary plant"],
        "scientific_name": "Pilea peperomioides",
        "family": "Urticaceae",
        "care": HOUSE,
    },
    {
        "id": "jade-plant",
        "common_names": ["Jade plant", "Money plant", "Friendship tree"],
        "scientific_name": "Crassula ovata",
        "family": "Crassulaceae",
        "care": SUCC,
    },
    {
        "id": "boston-fern",
        "common_names": ["Boston fern", "Sword fern"],
        "scientific_name": "Nephrolepis exaltata",
        "family": "Nephrolepidaceae",
        "care": HIGH,
    },
    {
        "id": "calathea-orbifolia",
        "common_names": ["Calathea orbifolia", "Prayer plant"],
        "scientific_name": "Goeppertia orbifolia",
        "family": "Marantaceae",
        "care": HIGH,
    },
    {
        "id": "bird-of-paradise",
        "common_names": ["Bird of paradise", "Crane flower"],
        "scientific_name": "Strelitzia reginae",
        "family": "Strelitziaceae",
        "care": OUTDOOR,
    },
    {
        "id": "string-of-pearls",
        "common_names": ["String of pearls"],
        "scientific_name": "Curio rowleyanus",
        "family": "Asteraceae",
        "care": SUCC,
    },
    {
        "id": "english-ivy",
        "common_names": ["English ivy", "Common ivy"],
        "scientific_name": "Hedera helix",
        "family": "Araliaceae",
        "care": HOUSE,
    },
    {
        "id": "tradescantia-zebrina",
        "common_names": ["Wandering dude", "Inch plant", "Zebrina"],
        "scientific_name": "Tradescantia zebrina",
        "family": "Commelinaceae",
        "care": HOUSE,
    },
    {
        "id": "african-violet",
        "common_names": ["African violet"],
        "scientific_name": "Streptocarpus ionanthus",
        "family": "Gesneriaceae",
        "care": HOUSE,
    },
    {
        "id": "anthurium",
        "common_names": ["Anthurium", "Flamingo flower"],
        "scientific_name": "Anthurium andraeanum",
        "family": "Araceae",
        "care": HIGH,
    },
    {
        "id": "dieffenbachia",
        "common_names": ["Dieffenbachia", "Dumb cane"],
        "scientific_name": "Dieffenbachia seguine",
        "family": "Araceae",
        "care": HOUSE,
    },
    {
        "id": "aglaonema",
        "common_names": ["Chinese evergreen", "Aglaonema"],
        "scientific_name": "Aglaonema commutatum",
        "family": "Araceae",
        "care": SHADE,
    },
    {
        "id": "dracaena-marginata",
        "common_names": ["Dragon tree", "Madagascar dragon tree"],
        "scientific_name": "Dracaena marginata",
        "family": "Asparagaceae",
        "care": HOUSE,
    },
    {
        "id": "parlor-palm",
        "common_names": ["Parlor palm", "Neanthe bella palm"],
        "scientific_name": "Chamaedorea elegans",
        "family": "Arecaceae",
        "care": SHADE,
    },
    {
        "id": "areca-palm",
        "common_names": ["Areca palm", "Butterfly palm"],
        "scientific_name": "Dypsis lutescens",
        "family": "Arecaceae",
        "care": HOUSE,
    },
    {
        "id": "money-tree",
        "common_names": ["Money tree", "Guiana chestnut"],
        "scientific_name": "Pachira aquatica",
        "family": "Malvaceae",
        "care": HOUSE,
    },
    {
        "id": "schefflera",
        "common_names": ["Umbrella tree", "Schefflera"],
        "scientific_name": "Heptapleurum arboricola",
        "family": "Araliaceae",
        "care": HOUSE,
    },
    {
        "id": "philodendron-hederaceum",
        "common_names": ["Heartleaf philodendron", "Sweetheart plant"],
        "scientific_name": "Philodendron hederaceum",
        "family": "Araceae",
        "care": HOUSE,
    },
    {
        "id": "swiss-cheese-vine",
        "common_names": ["Swiss cheese vine", "Monstera adansonii"],
        "scientific_name": "Monstera adansonii",
        "family": "Araceae",
        "care": HOUSE,
    },
    {
        "id": "calathea-makoyana",
        "common_names": ["Peacock plant", "Cathedral windows"],
        "scientific_name": "Goeppertia makoyana",
        "family": "Marantaceae",
        "care": HIGH,
    },
    {
        "id": "maranta-leuconeura",
        "common_names": ["Prayer plant", "Rabbit tracks"],
        "scientific_name": "Maranta leuconeura",
        "family": "Marantaceae",
        "care": HIGH,
    },
    {
        "id": "caladium",
        "common_names": ["Caladium", "Angel wings"],
        "scientific_name": "Caladium bicolor",
        "family": "Araceae",
        "care": HIGH,
    },
    {
        "id": "croton",
        "common_names": ["Croton", "Garden croton"],
        "scientific_name": "Codiaeum variegatum",
        "family": "Euphorbiaceae",
        "care": HOUSE,
    },
    {
        "id": "ponytail-palm",
        "common_names": ["Ponytail palm", "Elephant foot tree"],
        "scientific_name": "Beaucarnea recurvata",
        "family": "Asparagaceae",
        "care": SUCC,
    },
    {
        "id": "yucca",
        "common_names": ["Yucca", "Spineless yucca"],
        "scientific_name": "Yucca gigantea",
        "family": "Asparagaceae",
        "care": SUCC,
    },
    {
        "id": "christmas-cactus",
        "common_names": ["Christmas cactus", "Holiday cactus"],
        "scientific_name": "Schlumbergera truncata",
        "family": "Cactaceae",
        "care": HOUSE,
    },
    {
        "id": "christmas-cactus-buckleyi",
        "common_names": ["True Christmas cactus"],
        "scientific_name": "Schlumbergera bridgesii",
        "family": "Cactaceae",
        "care": HOUSE,
    },
    {
        "id": "haworthia",
        "common_names": ["Zebra haworthia", "Zebra plant"],
        "scientific_name": "Haworthiopsis attenuata",
        "family": "Asphodelaceae",
        "care": SUCC,
    },
    {
        "id": "echeveria-elegans",
        "common_names": ["Mexican snowball", "Echeveria"],
        "scientific_name": "Echeveria elegans",
        "family": "Crassulaceae",
        "care": SUCC,
    },
    {
        "id": "burros-tail",
        "common_names": ["Burro's tail", "Donkey's tail"],
        "scientific_name": "Sedum morganianum",
        "family": "Crassulaceae",
        "care": SUCC,
    },
    {
        "id": "hens-and-chicks",
        "common_names": ["Hens and chicks", "Houseleek"],
        "scientific_name": "Sempervivum tectorum",
        "family": "Crassulaceae",
        "care": SUCC,
    },
    {
        "id": "prickly-pear",
        "common_names": ["Prickly pear", "Opuntia"],
        "scientific_name": "Opuntia ficus-indica",
        "family": "Cactaceae",
        "care": SUCC,
    },
    {
        "id": "saguaro",
        "common_names": ["Saguaro"],
        "scientific_name": "Carnegiea gigantea",
        "family": "Cactaceae",
        "care": SUCC,
    },
    {
        "id": "barrel-cactus",
        "common_names": ["Golden barrel cactus"],
        "scientific_name": "Kroenleinia grusonii",
        "family": "Cactaceae",
        "care": SUCC,
    },
    {
        "id": "lithops",
        "common_names": ["Living stones", "Lithops"],
        "scientific_name": "Lithops lesliei",
        "family": "Aizoaceae",
        "care": SUCC,
    },
    # Carnivorous / unusual
    {
        "id": "pitcher-plant",
        "common_names": ["Purple pitcher plant"],
        "scientific_name": "Sarracenia purpurea",
        "family": "Sarraceniaceae",
        "care": CARN,
    },
    {
        "id": "sundew",
        "common_names": ["Round-leaved sundew", "Sundew"],
        "scientific_name": "Drosera rotundifolia",
        "family": "Droseraceae",
        "care": CARN,
    },
    {
        "id": "nepenthes",
        "common_names": ["Tropical pitcher plant", "Nepenthes"],
        "scientific_name": "Nepenthes alata",
        "family": "Nepenthaceae",
        "care": CARN,
    },
    # Herbs
    {
        "id": "basil",
        "common_names": ["Basil", "Sweet basil"],
        "scientific_name": "Ocimum basilicum",
        "family": "Lamiaceae",
        "care": HERB,
    },
    {
        "id": "mint",
        "common_names": ["Mint", "Spearmint"],
        "scientific_name": "Mentha spicata",
        "family": "Lamiaceae",
        "care": HERB,
    },
    {
        "id": "rosemary",
        "common_names": ["Rosemary"],
        "scientific_name": "Salvia rosmarinus",
        "family": "Lamiaceae",
        "care": HERB,
    },
    {
        "id": "lavender",
        "common_names": ["Lavender", "English lavender"],
        "scientific_name": "Lavandula angustifolia",
        "family": "Lamiaceae",
        "care": HERB,
    },
    {
        "id": "thyme",
        "common_names": ["Thyme", "Common thyme"],
        "scientific_name": "Thymus vulgaris",
        "family": "Lamiaceae",
        "care": HERB,
    },
    {
        "id": "oregano",
        "common_names": ["Oregano"],
        "scientific_name": "Origanum vulgare",
        "family": "Lamiaceae",
        "care": HERB,
    },
    {
        "id": "sage",
        "common_names": ["Sage", "Common sage"],
        "scientific_name": "Salvia officinalis",
        "family": "Lamiaceae",
        "care": HERB,
    },
    {
        "id": "parsley",
        "common_names": ["Parsley"],
        "scientific_name": "Petroselinum crispum",
        "family": "Apiaceae",
        "care": HERB,
    },
    {
        "id": "cilantro",
        "common_names": ["Cilantro", "Coriander"],
        "scientific_name": "Coriandrum sativum",
        "family": "Apiaceae",
        "care": HERB,
    },
    {
        "id": "chives",
        "common_names": ["Chives"],
        "scientific_name": "Allium schoenoprasum",
        "family": "Amaryllidaceae",
        "care": HERB,
    },
    # Edibles / garden
    {
        "id": "tomato",
        "common_names": ["Tomato"],
        "scientific_name": "Solanum lycopersicum",
        "family": "Solanaceae",
        "care": OUTDOOR,
    },
    {
        "id": "strawberry",
        "common_names": ["Strawberry", "Garden strawberry"],
        "scientific_name": "Fragaria × ananassa",
        "family": "Rosaceae",
        "care": OUTDOOR,
    },
    {
        "id": "blueberry",
        "common_names": ["Blueberry", "Northern highbush blueberry"],
        "scientific_name": "Vaccinium corymbosum",
        "family": "Ericaceae",
        "care": OUTDOOR,
    },
    {
        "id": "sunflower",
        "common_names": ["Sunflower", "Common sunflower"],
        "scientific_name": "Helianthus annuus",
        "family": "Asteraceae",
        "care": OUTDOOR,
    },
    {
        "id": "marigold",
        "common_names": ["French marigold"],
        "scientific_name": "Tagetes patula",
        "family": "Asteraceae",
        "care": OUTDOOR,
    },
    {
        "id": "zinnia",
        "common_names": ["Zinnia"],
        "scientific_name": "Zinnia elegans",
        "family": "Asteraceae",
        "care": OUTDOOR,
    },
    {
        "id": "rose",
        "common_names": ["Rose", "Garden rose"],
        "scientific_name": "Rosa gallica",
        "family": "Rosaceae",
        "care": OUTDOOR,
    },
    {
        "id": "tulip",
        "common_names": ["Tulip"],
        "scientific_name": "Tulipa gesneriana",
        "family": "Liliaceae",
        "care": OUTDOOR,
    },
    {
        "id": "daffodil",
        "common_names": ["Daffodil", "Wild daffodil"],
        "scientific_name": "Narcissus pseudonarcissus",
        "family": "Amaryllidaceae",
        "care": OUTDOOR,
    },
    {
        "id": "hyacinth",
        "common_names": ["Hyacinth", "Common hyacinth"],
        "scientific_name": "Hyacinthus orientalis",
        "family": "Asparagaceae",
        "care": OUTDOOR,
    },
    {
        "id": "lily-of-the-valley",
        "common_names": ["Lily of the valley"],
        "scientific_name": "Convallaria majalis",
        "family": "Asparagaceae",
        "care": SHADE,
    },
    {
        "id": "hosta",
        "common_names": ["Hosta", "Plantain lily"],
        "scientific_name": "Hosta plantaginea",
        "family": "Asparagaceae",
        "care": SHADE,
    },
    {
        "id": "hydrangea",
        "common_names": ["Bigleaf hydrangea", "Hydrangea"],
        "scientific_name": "Hydrangea macrophylla",
        "family": "Hydrangeaceae",
        "care": OUTDOOR,
    },
    {
        "id": "peony",
        "common_names": ["Chinese peony", "Peony"],
        "scientific_name": "Paeonia lactiflora",
        "family": "Paeoniaceae",
        "care": OUTDOOR,
    },
    {
        "id": "japanese-maple",
        "common_names": ["Japanese maple"],
        "scientific_name": "Acer palmatum",
        "family": "Sapindaceae",
        "care": OUTDOOR,
    },
    {
        "id": "olive-tree",
        "common_names": ["Olive", "Olive tree"],
        "scientific_name": "Olea europaea",
        "family": "Oleaceae",
        "care": OUTDOOR,
    },
    {
        "id": "lemon-tree",
        "common_names": ["Lemon", "Lemon tree"],
        "scientific_name": "Citrus × limon",
        "family": "Rutaceae",
        "care": OUTDOOR,
    },
    {
        "id": "avocado",
        "common_names": ["Avocado"],
        "scientific_name": "Persea americana",
        "family": "Lauraceae",
        "care": OUTDOOR,
    },
    # More tropicals / favorites
    {
        "id": "banana-plant",
        "common_names": ["Banana", "Banana plant"],
        "scientific_name": "Musa acuminata",
        "family": "Musaceae",
        "care": HIGH,
    },
    {
        "id": "birdsnest-fern",
        "common_names": ["Bird's-nest fern"],
        "scientific_name": "Asplenium nidus",
        "family": "Aspleniaceae",
        "care": HIGH,
    },
    {
        "id": "maidenhair-fern",
        "common_names": ["Maidenhair fern"],
        "scientific_name": "Adiantum raddianum",
        "family": "Pteridaceae",
        "care": HIGH,
    },
    {
        "id": "staghorn-fern",
        "common_names": ["Staghorn fern"],
        "scientific_name": "Platycerium bifurcatum",
        "family": "Polypodiaceae",
        "care": HIGH,
    },
    {
        "id": "hoya-carnosa",
        "common_names": ["Wax plant", "Hoya"],
        "scientific_name": "Hoya carnosa",
        "family": "Apocynaceae",
        "care": HOUSE,
    },
    {
        "id": "string-of-hearts",
        "common_names": ["String of hearts", "Rosary vine"],
        "scientific_name": "Ceropegia woodii",
        "family": "Apocynaceae",
        "care": SUCC,
    },
    {
        "id": "peperomia-obtusifolia",
        "common_names": ["Baby rubber plant", "Pepper face"],
        "scientific_name": "Peperomia obtusifolia",
        "family": "Piperaceae",
        "care": HOUSE,
    },
    {
        "id": "watermelon-peperomia",
        "common_names": ["Watermelon peperomia"],
        "scientific_name": "Peperomia argyreia",
        "family": "Piperaceae",
        "care": HOUSE,
    },
    {
        "id": "chinese-evergreen-pictum",
        "common_names": ["Red aglaonema"],
        "scientific_name": "Aglaonema",
        "family": "Araceae",
        "care": SHADE,
    },
    {
        "id": "cast-iron-plant",
        "common_names": ["Cast iron plant"],
        "scientific_name": "Aspidistra elatior",
        "family": "Asparagaceae",
        "care": SHADE,
    },
    {
        "id": "asparagus-fern",
        "common_names": ["Asparagus fern"],
        "scientific_name": "Asparagus setaceus",
        "family": "Asparagaceae",
        "care": HOUSE,
    },
    {
        "id": "bamboo-palm",
        "common_names": ["Bamboo palm", "Reed palm"],
        "scientific_name": "Chamaedorea seifrizii",
        "family": "Arecaceae",
        "care": HOUSE,
    },
    {
        "id": "kentia-palm",
        "common_names": ["Kentia palm", "Paradise palm"],
        "scientific_name": "Howea forsteriana",
        "family": "Arecaceae",
        "care": HOUSE,
    },
    {
        "id": "fiddle-leaf-fig-bambino",
        "common_names": ["Weeping fig", "Benjamin fig"],
        "scientific_name": "Ficus benjamina",
        "family": "Moraceae",
        "care": HOUSE,
    },
    {
        "id": "oxalis-triangularis",
        "common_names": ["Purple shamrock", "False shamrock"],
        "scientific_name": "Oxalis triangularis",
        "family": "Oxalidaceae",
        "care": HOUSE,
    },
    {
        "id": "begonia-rex",
        "common_names": ["Rex begonia"],
        "scientific_name": "Begonia rex",
        "family": "Begoniaceae",
        "care": HIGH,
    },
    {
        "id": "polka-dot-plant",
        "common_names": ["Polka dot plant"],
        "scientific_name": "Hypoestes phyllostachya",
        "family": "Acanthaceae",
        "care": HOUSE,
    },
    {
        "id": "nerve-plant",
        "common_names": ["Nerve plant", "Mosaic plant"],
        "scientific_name": "Fittonia albivenis",
        "family": "Acanthaceae",
        "care": HIGH,
    },
    {
        "id": "aluminum-plant",
        "common_names": ["Aluminum plant"],
        "scientific_name": "Pilea cadierei",
        "family": "Urticaceae",
        "care": HOUSE,
    },
    {
        "id": "swedish-ivy",
        "common_names": ["Swedish ivy", "Creeping Charlie"],
        "scientific_name": "Plectranthus verticillatus",
        "family": "Lamiaceae",
        "care": HOUSE,
    },
    {
        "id": "coleus",
        "common_names": ["Coleus", "Painted nettle"],
        "scientific_name": "Coleus scutellarioides",
        "family": "Lamiaceae",
        "care": HOUSE,
    },
    {
        "id": "impatiens",
        "common_names": ["Impatiens", "Busy Lizzie"],
        "scientific_name": "Impatiens walleriana",
        "family": "Balsaminaceae",
        "care": SHADE,
    },
    {
        "id": "geranium",
        "common_names": ["Geranium", "Zonal geranium"],
        "scientific_name": "Pelargonium zonale",
        "family": "Geraniaceae",
        "care": OUTDOOR,
    },
    {
        "id": "petunia",
        "common_names": ["Petunia"],
        "scientific_name": "Petunia × atkinsiana",
        "family": "Solanaceae",
        "care": OUTDOOR,
    },
    {
        "id": "chrysanthemum",
        "common_names": ["Chrysanthemum", "Garden mum"],
        "scientific_name": "Chrysanthemum morifolium",
        "family": "Asteraceae",
        "care": OUTDOOR,
    },
    {
        "id": "daisy",
        "common_names": ["Oxeye daisy"],
        "scientific_name": "Leucanthemum vulgare",
        "family": "Asteraceae",
        "care": OUTDOOR,
    },
    {
        "id": "dandelion",
        "common_names": ["Dandelion", "Common dandelion"],
        "scientific_name": "Taraxacum officinale",
        "family": "Asteraceae",
        "care": OUTDOOR,
    },
    {
        "id": "clover",
        "common_names": ["White clover"],
        "scientific_name": "Trifolium repens",
        "family": "Fabaceae",
        "care": OUTDOOR,
    },
    {
        "id": "bamboo",
        "common_names": ["Golden bamboo", "Bamboo"],
        "scientific_name": "Phyllostachys aurea",
        "family": "Poaceae",
        "care": OUTDOOR,
    },
    {
        "id": "lucky-bamboo",
        "common_names": ["Lucky bamboo"],
        "scientific_name": "Dracaena sanderiana",
        "family": "Asparagaceae",
        "care": HOUSE,
    },
    {
        "id": "corn-plant",
        "common_names": ["Corn plant", "Mass cane"],
        "scientific_name": "Dracaena fragrans",
        "family": "Asparagaceae",
        "care": HOUSE,
    },
    {
        "id": "ti-plant",
        "common_names": ["Ti plant", "Cordyline"],
        "scientific_name": "Cordyline fruticosa",
        "family": "Asparagaceae",
        "care": HOUSE,
    },
    {
        "id": "bromeliad",
        "common_names": ["Urn plant", "Silver vase"],
        "scientific_name": "Aechmea fasciata",
        "family": "Bromeliaceae",
        "care": HOUSE,
    },
    {
        "id": "guzmania",
        "common_names": ["Guzmania", "Scarlet star"],
        "scientific_name": "Guzmania lingulata",
        "family": "Bromeliaceae",
        "care": HIGH,
    },
    {
        "id": "plumeria",
        "common_names": ["Plumeria", "Frangipani"],
        "scientific_name": "Plumeria rubra",
        "family": "Apocynaceae",
        "care": OUTDOOR,
    },
    {
        "id": "hibiscus",
        "common_names": ["Hibiscus", "Chinese hibiscus"],
        "scientific_name": "Hibiscus rosa-sinensis",
        "family": "Malvaceae",
        "care": OUTDOOR,
    },
    {
        "id": "bougainvillea",
        "common_names": ["Bougainvillea"],
        "scientific_name": "Bougainvillea glabra",
        "family": "Nyctaginaceae",
        "care": OUTDOOR,
    },
    {
        "id": "jasmine",
        "common_names": ["Common jasmine", "Poet's jasmine"],
        "scientific_name": "Jasminum officinale",
        "family": "Oleaceae",
        "care": OUTDOOR,
    },
    {
        "id": "gardenia",
        "common_names": ["Gardenia", "Cape jasmine"],
        "scientific_name": "Gardenia jasminoides",
        "family": "Rubiaceae",
        "care": HIGH,
    },
    {
        "id": "camellia",
        "common_names": ["Camellia", "Japanese camellia"],
        "scientific_name": "Camellia japonica",
        "family": "Theaceae",
        "care": OUTDOOR,
    },
    {
        "id": "azalea",
        "common_names": ["Azalea"],
        "scientific_name": "Rhododendron simsii",
        "family": "Ericaceae",
        "care": OUTDOOR,
    },
    {
        "id": "rhododendron",
        "common_names": ["Rhododendron"],
        "scientific_name": "Rhododendron ponticum",
        "family": "Ericaceae",
        "care": OUTDOOR,
    },
    {
        "id": "boxwood",
        "common_names": ["Boxwood", "Common box"],
        "scientific_name": "Buxus sempervirens",
        "family": "Buxaceae",
        "care": OUTDOOR,
    },
    {
        "id": "lavender-cotton",
        "common_names": ["Lavender cotton", "Santolina"],
        "scientific_name": "Santolina chamaecyparissus",
        "family": "Asteraceae",
        "care": OUTDOOR,
    },
    {
        "id": "echinacea",
        "common_names": ["Purple coneflower", "Echinacea"],
        "scientific_name": "Echinacea purpurea",
        "family": "Asteraceae",
        "care": OUTDOOR,
    },
    {
        "id": "black-eyed-susan",
        "common_names": ["Black-eyed Susan"],
        "scientific_name": "Rudbeckia hirta",
        "family": "Asteraceae",
        "care": OUTDOOR,
    },
    {
        "id": "bee-balm",
        "common_names": ["Bee balm", "Scarlet beebalm"],
        "scientific_name": "Monarda didyma",
        "family": "Lamiaceae",
        "care": OUTDOOR,
    },
    {
        "id": "milkweed",
        "common_names": ["Butterfly weed", "Milkweed"],
        "scientific_name": "Asclepias tuberosa",
        "family": "Apocynaceae",
        "care": OUTDOOR,
    },
    {
        "id": "kale",
        "common_names": ["Kale"],
        "scientific_name": "Brassica oleracea",
        "family": "Brassicaceae",
        "care": OUTDOOR,
    },
    {
        "id": "lettuce",
        "common_names": ["Lettuce", "Garden lettuce"],
        "scientific_name": "Lactuca sativa",
        "family": "Asteraceae",
        "care": OUTDOOR,
    },
    {
        "id": "pepper",
        "common_names": ["Bell pepper", "Sweet pepper"],
        "scientific_name": "Capsicum annuum",
        "family": "Solanaceae",
        "care": OUTDOOR,
    },
    {
        "id": "cucumber",
        "common_names": ["Cucumber"],
        "scientific_name": "Cucumis sativus",
        "family": "Cucurbitaceae",
        "care": OUTDOOR,
    },
    {
        "id": "pumpkin",
        "common_names": ["Pumpkin"],
        "scientific_name": "Cucurbita pepo",
        "family": "Cucurbitaceae",
        "care": OUTDOOR,
    },
    {
        "id": "grapevine",
        "common_names": ["Grape", "Wine grape"],
        "scientific_name": "Vitis vinifera",
        "family": "Vitaceae",
        "care": OUTDOOR,
    },
    {
        "id": "apple-tree",
        "common_names": ["Apple", "Apple tree"],
        "scientific_name": "Malus domestica",
        "family": "Rosaceae",
        "care": OUTDOOR,
    },
    {
        "id": "oak",
        "common_names": ["English oak", "Oak"],
        "scientific_name": "Quercus robur",
        "family": "Fagaceae",
        "care": OUTDOOR,
    },
    {
        "id": "maple",
        "common_names": ["Sugar maple"],
        "scientific_name": "Acer saccharum",
        "family": "Sapindaceae",
        "care": OUTDOOR,
    },
    {
        "id": "pine",
        "common_names": ["Scots pine", "Pine"],
        "scientific_name": "Pinus sylvestris",
        "family": "Pinaceae",
        "care": OUTDOOR,
    },
    {
        "id": "ginkgo",
        "common_names": ["Ginkgo", "Maidenhair tree"],
        "scientific_name": "Ginkgo biloba",
        "family": "Ginkgoaceae",
        "care": OUTDOOR,
    },
    {
        "id": "magnolia",
        "common_names": ["Southern magnolia"],
        "scientific_name": "Magnolia grandiflora",
        "family": "Magnoliaceae",
        "care": OUTDOOR,
    },
    {
        "id": "dogwood",
        "common_names": ["Flowering dogwood"],
        "scientific_name": "Cornus florida",
        "family": "Cornaceae",
        "care": OUTDOOR,
    },
    {
        "id": "redbud",
        "common_names": ["Eastern redbud"],
        "scientific_name": "Cercis canadensis",
        "family": "Fabaceae",
        "care": OUTDOOR,
    },
    {
        "id": "wisteria",
        "common_names": ["Chinese wisteria"],
        "scientific_name": "Wisteria sinensis",
        "family": "Fabaceae",
        "care": OUTDOOR,
    },
    {
        "id": "clematis",
        "common_names": ["Clematis"],
        "scientific_name": "Clematis vitalba",
        "family": "Ranunculaceae",
        "care": OUTDOOR,
    },
    {
        "id": "morning-glory",
        "common_names": ["Morning glory"],
        "scientific_name": "Ipomoea purpurea",
        "family": "Convolvulaceae",
        "care": OUTDOOR,
    },
    {
        "id": "nasturtium",
        "common_names": ["Nasturtium", "Garden nasturtium"],
        "scientific_name": "Tropaeolum majus",
        "family": "Tropaeolaceae",
        "care": OUTDOOR,
    },
    {
        "id": "pansy",
        "common_names": ["Pansy"],
        "scientific_name": "Viola × wittrockiana",
        "family": "Violaceae",
        "care": OUTDOOR,
    },
    {
        "id": "violet",
        "common_names": ["Sweet violet"],
        "scientific_name": "Viola odorata",
        "family": "Violaceae",
        "care": SHADE,
    },
    {
        "id": "snapdragon",
        "common_names": ["Snapdragon"],
        "scientific_name": "Antirrhinum majus",
        "family": "Plantaginaceae",
        "care": OUTDOOR,
    },
    {
        "id": "foxglove",
        "common_names": ["Foxglove"],
        "scientific_name": "Digitalis purpurea",
        "family": "Plantaginaceae",
        "care": OUTDOOR,
    },
    {
        "id": "hollyhock",
        "common_names": ["Hollyhock"],
        "scientific_name": "Alcea rosea",
        "family": "Malvaceae",
        "care": OUTDOOR,
    },
    {
        "id": "delphinium",
        "common_names": ["Delphinium", "Candle larkspur"],
        "scientific_name": "Delphinium elatum",
        "family": "Ranunculaceae",
        "care": OUTDOOR,
    },
    {
        "id": "lupine",
        "common_names": ["Large-leaved lupine", "Lupine"],
        "scientific_name": "Lupinus polyphyllus",
        "family": "Fabaceae",
        "care": OUTDOOR,
    },
    {
        "id": "iris",
        "common_names": ["Bearded iris", "German iris"],
        "scientific_name": "Iris germanica",
        "family": "Iridaceae",
        "care": OUTDOOR,
    },
    {
        "id": "gladiolus",
        "common_names": ["Gladiolus", "Sword lily"],
        "scientific_name": "Gladiolus × hortulanus",
        "family": "Iridaceae",
        "care": OUTDOOR,
    },
    {
        "id": "canna",
        "common_names": ["Canna lily", "Canna"],
        "scientific_name": "Canna indica",
        "family": "Cannaceae",
        "care": OUTDOOR,
    },
    {
        "id": "calla-lily",
        "common_names": ["Calla lily", "Arum lily"],
        "scientific_name": "Zantedeschia aethiopica",
        "family": "Araceae",
        "care": HIGH,
    },
    {
        "id": "amaryllis",
        "common_names": ["Amaryllis", "Hippeastrum"],
        "scientific_name": "Hippeastrum",
        "family": "Amaryllidaceae",
        "care": HOUSE,
    },
    {
        "id": "paperwhite",
        "common_names": ["Paperwhite", "Paperwhite narcissus"],
        "scientific_name": "Narcissus papyraceus",
        "family": "Amaryllidaceae",
        "care": HOUSE,
    },
    {
        "id": "crocus",
        "common_names": ["Spring crocus"],
        "scientific_name": "Crocus vernus",
        "family": "Iridaceae",
        "care": OUTDOOR,
    },
    {
        "id": "snowdrop",
        "common_names": ["Snowdrop", "Common snowdrop"],
        "scientific_name": "Galanthus nivalis",
        "family": "Amaryllidaceae",
        "care": OUTDOOR,
    },
    {
        "id": "bluebell",
        "common_names": ["English bluebell"],
        "scientific_name": "Hyacinthoides non-scripta",
        "family": "Asparagaceae",
        "care": SHADE,
    },
    {
        "id": "bleeding-heart",
        "common_names": ["Bleeding heart"],
        "scientific_name": "Lamprocapnos spectabilis",
        "family": "Papaveraceae",
        "care": SHADE,
    },
    {
        "id": "fern-leaf-lavender",
        "common_names": ["French lavender"],
        "scientific_name": "Lavandula stoechas",
        "family": "Lamiaceae",
        "care": HERB,
    },
    {
        "id": "stevia",
        "common_names": ["Stevia", "Sweetleaf"],
        "scientific_name": "Stevia rebaudiana",
        "family": "Asteraceae",
        "care": HERB,
    },
    {
        "id": "lemongrass",
        "common_names": ["Lemongrass"],
        "scientific_name": "Cymbopogon citratus",
        "family": "Poaceae",
        "care": HERB,
    },
    {
        "id": "ginger",
        "common_names": ["Ginger"],
        "scientific_name": "Zingiber officinale",
        "family": "Zingiberaceae",
        "care": HIGH,
    },
    {
        "id": "turmeric",
        "common_names": ["Turmeric"],
        "scientific_name": "Curcuma longa",
        "family": "Zingiberaceae",
        "care": HIGH,
    },
    {
        "id": "cardamom",
        "common_names": ["Cardamom", "Green cardamom"],
        "scientific_name": "Elettaria cardamomum",
        "family": "Zingiberaceae",
        "care": HIGH,
    },
    {
        "id": "vanilla",
        "common_names": ["Vanilla orchid", "Vanilla"],
        "scientific_name": "Vanilla planifolia",
        "family": "Orchidaceae",
        "care": ORCH,
    },
    {
        "id": "cattleya",
        "common_names": ["Cattleya orchid"],
        "scientific_name": "Cattleya labiata",
        "family": "Orchidaceae",
        "care": ORCH,
    },
    {
        "id": "dendrobium",
        "common_names": ["Dendrobium orchid"],
        "scientific_name": "Dendrobium nobile",
        "family": "Orchidaceae",
        "care": ORCH,
    },
    {
        "id": "oncidium",
        "common_names": ["Dancing-lady orchid", "Oncidium"],
        "scientific_name": "Oncidium",
        "family": "Orchidaceae",
        "care": ORCH,
    },
    {
        "id": "venus-slipper",
        "common_names": ["Lady slipper orchid", "Paphiopedilum"],
        "scientific_name": "Paphiopedilum",
        "family": "Orchidaceae",
        "care": ORCH,
    },
]
